### ISSUE TITLE
V2 Roadmap

### ISSUE THREAD

**Issue by 2nthony** [dvanjs/dvan#12]
### Dependency updates

- [x] webpack-chain v5
- [ ] css-loader v2

### starter

- [x] `create-dvan-app`

### plugins

- [ ] `vue-static`(plugin-ssg) WIP
- [ ] `plugin-pwa`(important)

### config

- [ ] `evergreen` Only targeting evergreen browsers.

### command

- [x] `eject-html` Eject built-in default HTML template that you can tweak it to fit your needs. (from Poi)
- [x] ~~`vue-sfc` Develop only a .vue file. Will release in `v2.2.0`~~

### Built-in
- [x] Use `webpackHotDevClient.js` for HMR.
- [ ] loading-screen

List for now.
